(load "11c.scm")

(define saver
  (make-machine
	'(a b c val)
	(list (list '* *))
	'((assign a (const 3))
	  (assign b (const 4))
	  (assign c (const 2))
	  (save a)
	  (save b)
	  (save c)
	  (save c)
	  (save c)
	  (save c)
	  (assign a (const 1))
	  (assign b (const 1))
	  (assign c (const 5))
	  (restore a)
	  (restore b)
	  (assign val (const 1))
	  (assign val (op *) (reg val) (reg a))
	  (assign val (op *) (reg val) (reg b))
	  (assign val (op *) (reg val) (reg c)))))

((lambda () 
   (start saver)
   (newline) (display "Should be 60:")
   (get-register-contents saver 'val)))
