(define (pascal-element row col)
  (cond ((> col row) 0)
		((< col 1) 0)
		((= row 1) 1)
		(else (+ (pascal-element (- row 1) col)
				 (pascal-element (- row 1) (- col 1))))))

(pascal-element 0 0)
(pascal-element 1 1)
(pascal-element 2 1)
(pascal-element 2 2)
(pascal-element 3 1)
(pascal-element 3 2)
(pascal-element 3 3)
