(define (make-monitored f)
  (let ((count 0))
	(lambda (x)
	  (cond ((equal? x 'how-many-calls?) count)
			((equal? x 'reset-count) (set! count 0))
			(else (set! count (1+ count))
				  (f x))))))

(define s (make-monitored sqrt))
(s 100)
(s 400)
(s 'how-many-calls?)
(s 'reset-count)
(s 'how-many-calls?)
(s 4)
(s 'how-many-calls?)
